module.exports = {
  products: [
    {
      _id: '1',
      name: 'Knight Bracelet',
      category: 'Shirts',
      image: '/images/pulsera (1).JPEG',
      price: 150,
      brand: 'Seven Pearls',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Fire Ball Bracelet',
      category: 'Beaded Collection',
      image: '/images/pulsera (33).JPEG',
      price: 70,
      brand: 'Seven Pearls',
      rating: 5,
      numReviews: 51,
    },
    {
      _id: '3',
      name: 'Bull Bracelet',
      category: 'Animal Colletion',
      image: '/images/pulsera (2).JPEG',
      price: 159,
      brand: 'Seven Pearls',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'Dragon Bracelet',
      category: 'Beaded Collection',
      image: '/images/pulsera (32).JPEG',
      price: 90,
      brand: 'Seven Pearls',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Dark Soul',
      category: 'Beaded Collection',
      image: '/images/pulsera (3).JPEG',
      price: 119,
      brand: 'Seven Pearls',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Skull Bracelet',
      category: 'Beaded Collection',
      image: '/images/pulsera (31).JPEG',
      price: 119,
      brand: 'Seven Pearls',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '7',
      name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
      category: 'Shirts',
      image: '/images/pulsera (4).JPEG',
      price: 70,
      brand: 'Nike',
      rating: 5,
      numReviews: 51,
    },
    {
      _id: '8',
      name: 'Adidas Mens Long Sleeve Hoodie',
      category: 'Shirts',
      image: '/images/pulsera (30).JPEG',
      price: 59,
      brand: 'Adidas',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '9',
      name: 'Under Armour Mens Sportstyle Tricot Joggers',
      category: 'Pants',
      image: '/images/pulsera (5).JPEG',
      price: 90,
      brand: 'Under Armour',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '10',
      name: 'Champion Mens Graphic Powerblend Fleece Jogger',
      category: 'Pants',
      image: '/images/pulsera (29).JPEG',
      price: 119,
      brand: 'Champion',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '11',
      name: 'Champion Mens Graphic Powerblend Fleece Jogger',
      category: 'Pants',
      image: '/images/pulsera (6).JPEG',
      price: 119,
      brand: 'Champion',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '12',
      name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
      category: 'Pants',
      image: '/images/pulsera (28).JPEG',
      price: 85,
      brand: 'Aelfric Eden',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};
