module.exports = {
  products: [
    {
      _id: '1',
      name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
      category: 'Shirts',
      image: '/images/pulsera (1).JPEG',
      price: 58,
      brand: 'Hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
      category: 'Shirts',
      image: '/images/pulsera (2).JPEG',
      price: 70,
      brand: 'Nike',
      rating: 5,
      numReviews: 51,
    },
    {
      _id: '3',
      name: 'Adidas Mens Long Sleeve Hoodie',
      category: 'Shirts',
      image: '/images/pulsera (3).JPEG',
      price: 69,
      brand: 'Adidas',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'Under Armour Mens Sportstyle Tricot Joggers',
      category: 'Pants',
      image: '/images/pulsera (4).JPEG',
      price: 100,
      brand: 'Under Armour',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Champion Mens Graphic Powerblend Fleece Jogger',
      category: 'Pants',
      image: '/images/pulsera (5).JPEG',
      price: 129,
      brand: 'Champion',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
      category: 'Pants',
      image: '/images/pulsera (6).JPEG',
      price: 75,
      brand: 'Aelfric Eden',
      rating: 4.5,
      numReviews: 45,
      countInStock: 7,
    },
  ],
};
